# For help visit following page:
# https://fromthebottomoftheheap.net/2020/04/30/rendering-your-readme-with-github-actions/
name: render readme

# Controls when the action will run
on:
  push:
    branches: [main, master]

jobs:
  render:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      
      # Install dependencies
      - name: Install cURL Headers
        run: sudo apt-get update && sudo apt-get install libcurl4-openssl-dev libharfbuzz-dev libfribidi-dev libfontconfig1-dev
      
      # Install packages needed
      - name: install required packages
        run: Rscript -e 'install.packages(c("devtools", "rmarkdown", "yamlme"), dependencies = TRUE)'
      
      # Install packages needed from GitHub
      - name: install from GitHub
        run: Rscript -e 'library(devtools);install_github("kamapu/biblio", dependencies = TRUE)'
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      
      # Render README.md using rmarkdown
      - name: render README
        run: Rscript -e 'rmarkdown::render("README.Rmd")'
      
      - name: commit rendered README
        run: |
          git add README.md && git commit README.md -m 'Re-build README.Rmd' || echo "No changes to commit"
          git push https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git HEAD:${{ github.ref }} || echo "No changes to commit"
